#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TAG="${1:-v1.8.2}"
REPO="ggml-org/whisper.cpp"
RAW_URL="https://raw.githubusercontent.com/${REPO}/${TAG}/models/download-ggml-model.sh"
OUT="${2:-${ROOT}/art/voice_models.generated.zig}"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch_text() {
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url"
    return
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -qO- "$url"
    return
  fi
  echo "error: need curl or wget" >&2
  exit 1
}

fetch_text "$RAW_URL" > "$TMP"

base_url=$(awk 'match($0, /(BASE_URL|base_url|URL_BASE|url_base)[[:space:]]*=[[:space:]]*"?([^" ]+)"?/, m) { print m[2]; exit }' "$TMP" || true)
if [[ -z "$base_url" ]]; then
  src_var=$(awk 'match($0, /^src="([^"]+)"/, m) { print m[1]; exit }' "$TMP" || true)
  pfx_var=$(awk 'match($0, /^pfx="([^"]+)"/, m) { print m[1]; exit }' "$TMP" || true)
  if [[ -n "$src_var" && -n "$pfx_var" ]]; then
    base_url="${src_var}/${pfx_var}"
    base_url="${base_url%/ggml}"
    base_url="${base_url%-ggml}"
  fi
fi
if [[ -z "$base_url" ]]; then
  echo "error: could not find base URL in upstream script" >&2
  exit 1
fi
# Normalize base_url to pinned tag.
if [[ "$base_url" == *"/resolve/"*"/" ]]; then
  base_url="$(echo "$base_url" | sed -E "s@/resolve/[^/]+/@/resolve/${TAG}/@")"
fi
case "$base_url" in
  */) ;;
  *) base_url="${base_url}/" ;;
esac

# Parse SHA256 maps.
declare -A sha_map
while read -r name hash; do
  [[ -n "$name" && -n "$hash" ]] || continue
  sha_map["$name"]="$hash"
done < <(awk 'match($0, /(MODEL_SHA256|model_sha256)\["([^"]+)"\]="?([0-9a-f]{64})"?/, m) { print m[2], m[3] }' "$TMP")

while read -r name hash; do
  [[ -n "$name" && -n "$hash" ]] || continue
  name="${name,,}"
  name="${name/_en/.en}"
  sha_map["$name"]="$hash"
done < <(awk 'match($0, /SHA256_([A-Za-z0-9_]+)="?([0-9a-f]{64})"?/, m) { print m[1], m[2] }' "$TMP")

# Parse model URLs for filenames when available.
declare -A file_map
while read -r name file; do
  [[ -n "$name" && -n "$file" ]] || continue
  file_map["$name"]="$file"
done < <(awk 'match($0, /(MODEL_URL|model_url)\["([^"]+)"\]="?([^\"]*ggml-[^\"/]+\.bin)/, m) { file=m[3]; sub(/^.*\//,"",file); print m[2], file }' "$TMP")

supported=(tiny base small medium large tiny.en base.en small.en medium.en)
missing=0

fetch_sha256() {
  local model="$1"
  local url="https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-${model}.bin"
  local html
  html="$(fetch_text "$url" | tr '\n' ' ')"
  echo "$html" | sed -n 's/.*SHA256:<\\/dt>[[:space:]]*<dd[^>]*>\\([0-9a-f]\\{64\\}\\).*/\\1/p' | head -n 1
}

{
  echo "// Generated by scripts/voice_update_models.sh"
  echo "// Upstream: ${REPO}@${TAG}"
  echo "pub const upstream_tag = \"${TAG}\";"
  echo "pub const base_url = \"${base_url}\";"
  echo "pub const ModelEntry = struct { size: []const u8, filename: []const u8, sha256: []const u8 };"
  echo "pub const model_entries = [_]ModelEntry{";
  for name in "${supported[@]}"; do
    sha="${sha_map[$name]:-}"
    file="${file_map[$name]:-}"
    model_id="$name"
    if [[ "$name" == "large" ]]; then
      model_id="large-v3"
    fi
    if [[ -z "$file" ]]; then
      file="ggml-${model_id}.bin"
    fi
    if [[ -z "$sha" ]]; then
      sha="$(fetch_sha256 "$model_id")"
    fi
    if [[ -z "$sha" ]]; then
      echo "// missing sha256 for ${name}" >&2
      missing=1
      sha="<FILL_FROM_UPSTREAM>"
    fi
    echo "  .{ .size = \"${name}\", .filename = \"${file}\", .sha256 = \"${sha}\" },"
  done
  echo "};"
} > "$OUT"

if [[ "$missing" -ne 0 ]]; then
  echo "warning: one or more SHA-256 values were missing; check upstream script format" >&2
fi

echo "wrote: $OUT"
